require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'infapp' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'RNTextGradientView', :path => '../node_modules/react-native-text-gradient'

  pod 'react-native-blur', :path => '../node_modules/@react-native-community/blur'

  pod 'react-native-cameraroll', :path => '../node_modules/@react-native-community/cameraroll'

  pod 'react-native-image-resizer', :path => '../node_modules/react-native-image-resizer'

  pod 'RNFS', :path => '../node_modules/react-native-fs'

  pod 'RNTestFlight', :path => '../node_modules/react-native-test-flight'


  pod 'RNCMaskedView', :path => '../node_modules/@react-native-community/masked-view'

  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

  pod 'RNIap', :path => '../node_modules/react-native-iap'

  target 'infappTests' do
    inherit! :complete
    # Pods for testing
  end
  
  pod 'RNInputMask', :path => '../node_modules/react-native-text-input-mask/ios/InputMask'
  pod 'CodePush', :path => '../node_modules/react-native-code-push'

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # use_flipper! # update this part
  # post_install do |installer|
  #   flipper_post_install(installer)
  # end
end

target 'OneSignalNotificationServiceExtension' do
  pod 'OneSignal', '>= 3.0', '< 4.0'
end

target 'infapp-tvOS' do
  # Pods for infapp-tvOS

  target 'infapp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
